version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file:
        .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: olga1611/foodgram_backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static:/backend_static
      - media:/media/
    depends_on: 
      - db
      - nginx

  frontend:
    image: olga1611/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on: 
      - nginx

  nginx:
    image: olga1611/foodgram_gateway
    env_file: .env
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/ 
#      - ./nginx:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
    ports:
      - 9100:80
