version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file:
        .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: olga1611/foodgram_backend
    env_file: .env
    ports:
      - "9000:8000"
    volumes:
      - media:/media/
      - static:/backend_static
    depends_on: 
      - db

  frontend:
    image: olga1611/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: olga1611/foodgram_gateway
    env_file: .env
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend_build:/usr/share/nginx/html/frontend/
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - "8000:80"
    depends_on:
      - backend
